version: '3'

services:
  flask:
    build: flask/
    image: pyimgfilter_server
    container_name: pyimgfilter_server
    command: flask run --host=0.0.0.0
    volumes:
      - ./flask/code:/code
    ports:
      - "5000:5000"
    restart: always
